### ISSUE TITLE
Uncaught TypeError 

### ISSUE THREAD

**Issue by kmeekva** [jaxon-php/jaxon-utils#1]
After upgrading to jaxon-utils v1.1.3  we are getting the following TypeError:

```
PHP message: PHP Fatal error:  Uncaught TypeError: Argument 2 passed to Jaxon\Utils\Template\Context::__set() must be an instance of Jaxon\Utils\Template\mixed, string given, called in /www/tasker/vendor/jaxon-php/jaxon-utils/src/Template/Context.php on line 44 and defined in /www/tasker/vendor/jaxon-php/jaxon-utils/src/Template/Context.php:64
Stack trace:
#0 /www/tasker/vendor/jaxon-php/jaxon-utils/src/Template/Context.php(44): Jaxon\Utils\Template\Context->__set('sName', 'tasks_add_scree...')
#1 /www/tasker/vendor/jaxon-php/jaxon-utils/src/Template/TemplateEngine.php(83): Jaxon\Utils\Template\Context->__construct(Object(Jaxon\Utils\Template\TemplateEngine), Array)
#2 /www/tasker/vendor/jaxon-php/jaxon-utils/src/Template/TemplateEngine.php(123): Jaxon\Utils\Template\TemplateEngine->renderTemplate('/www/tasker/ven...', Array)
#3 /www/tasker/vendor/jaxon-php/jaxon-core/src/Plugin/Request/CallableFunction/CallableFunctionPlugin.php(198): Jaxon\Utils\Template\TemplateEngine->render('callables/funct...', Array)
#4 /www/tasker/vendor/jaxon-php/ in /www/tasker/vendor/jaxon-php/jaxon-utils/src/Template/Context.php on line 64" while reading response header from upstream, 
```

Looks like the setter function is expecting mixed type -- but is being called passing a string?

**Comment by feuzeu** [comment]
Hi,

Which version oh PHP are you using?

**Comment by feuzeu** [comment]
Hi,

Seems like PHP 7.x does not allow the usage of `mixed` as a type in function signature, while PHP 8.x does.
The issue is fixed in the [1.1.4 release](https://github.com/jaxon-php/jaxon-utils/releases/tag/v1.1.4).

**Comment by kmeekva** [comment]
We are running PHP 7.4.33
We'll test the 1.1.4 and report back if there are still issues.
Thanks for maintaining this package!

**Comment by kmeekva** [comment]
Confirmed version 1.1.4 works with PHP 7.4.33.  
Closing this issue.

**Comment by feuzeu** [comment]
> We are running PHP 7.4.33 We'll test the 1.1.4 and report back if there are still issues. Thanks for maintaining this package!

You're welcome.
